name: Build Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Plugin
      shell: powershell
      run: |
        # Корень репозитория теперь и есть корень SDK
        $env:MAXON_ROOTDIR = "${{ github.workspace }}"
        
        # Находим ваш файл проекта внутри репозитория
        $vcxPath = Get-ChildItem -Path "plugins" -Filter "*.vcxproj" -Recurse | Select-Object -First 1 -ExpandProperty FullName
        Write-Host "Found project: $vcxPath"

        # Отключаем все капризные предупреждения нового компилятора
        $env:CL = "/wd5220 /wd5219 /wd4003 /wd4834 /wd4477 /wd4244 /wd4267"

        # Просто собираем!
        # /p:BuildProjectReferences=true соберет и фреймворки, раз они в репо
        msbuild $vcxPath `
          /p:Configuration=Release `
          /p:Platform=x64 `
          /p:PlatformToolset=v143 `
          /p:MAXON_ROOTDIR="$env:MAXON_ROOTDIR" `
          /p:TreatWarningsAsErrors=false `
          /m

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: geometry_projection_win64
        path: |
          plugins/**/*.xdl64
          plugins/**/res/